[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shellfish_tracking = "9R7cojRLBMXbM4np25sFuL6R65F3XY8SARZkTxrNS4gh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
provider = { cluster = "localnet", wallet = "~/.config/solana/id.json", url = "http://127.0.0.1:8898" }
